server:
  port: 8080

spring:
  application:
    name: spring-boot-tutorial
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/tvseries?stringtype=unspecified&ApplicationName=tutorial
    username: postgres
    password: yeonsea
  jackson:
    date-format: yyyy-MM-dd #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization: 
      write-dates-as-timestamps: false #使用数值timestamp表示日期
      
mybatis.configuration.mapUnderscoreToCamelCase: true
      
logging:
  file: target/app.log
  level: 
    ROOT: WARN
    cn.devmgr: TRACE